### ISSUE TITLE
Export  `Document a` constraint?

### ISSUE THREAD

**Issue by teh** [knupfer/type-of-html#2]
I might be misunderstanding how the renderX functions are meant to be be used, but AFAICT right now I can't implement the following

```haskell
instance H.Document a => MimeRender THTML a where
    mimeRender _ = H.renderByteString 
```

because Document isn't publicly exported. Would it make sense to export Document?

**Comment by knupfer** [comment]
Yes, you're right. I didn't do that, because it would expose quite ugly internals.
Thinking about it, I could expose Document as a constraint synonym of a not exported constraint synonym...

**Comment by knupfer** [comment]
Just fixed this issue and pushed a new version to hackage.
If you have got any more ideas, I'd be glad to hear them.
