### ISSUE TITLE
"data-x" attributes?

### ISSUE THREAD

**Issue by swizzard** [knupfer/type-of-html#4]
Is there a way to add `data-x="y"`-type attributes to elements? I only see `Html.Attribute.data_`, which creates a bare `data="foo"` attribute.

**Comment by knupfer** [comment]
Well, at the moment you can define the following:
```haskell
customData :: (Convert a, Convert b) => a -> b -> Raw Builder
customData x y = Raw (unConv (convert " data-" <> convert x <> convert (Raw "=\"") <> convert y <> convert (Raw '"')))
```
And use it as follows:
```haskell
>>> div_A (customData "foo" "bar") "zot"

<div data-foo="bar">zot</div>
```

**Comment by knupfer** [comment]
Beware that it's quite easy to shoot yourself in the foot because of the custom attribute name. You have to ensure yourself that it's valid, it's simply not feasible to cater for that.

Do you think that a function like that would be worth it?
Alternatively, one could extend the `Attribute` kind, allowing for more fusion but forcing the use of proxies.

**Comment by swizzard** [comment]
AFAICT the other `Attribute`s are all nulladic, so I fear adding `data-` would be tricky/require refactoring way too much. I recognize the risk of invalid names, but I think honestly it's pretty low.

I do think a `customData` function would be useful; it's also an easy and relatively low-risk way to add interoperability with various js libraries etc. (Full disclosure, the reason I asked in the first place is that I was thinking about trying to combine `type-of-html` with [htmx](https://htmx.org/), which has its own custom attributes, but can also work with `data-`, e.g. `hx-post="/"` or `data-hx-post="/"`, and figured `data-` would be a lighter lift than cracking open the finely oiled type machinery of `type-of-html` to try to jam htmx attributes in.)

**Comment by knupfer** [comment]
So, I just uploaded a new version.
Now you can easily define custom attributes:
```haskell
hxPost :: a -> 'CustomA "hx-post" := a
hxPost = A.custom_

>>> div_A (hxPost "foo") "bar"
<div hx-post="foo">bar</div>
```
This is all on the type level, so you won't get any impact on the performance.
Please check if the design works for you or if something is missing.
regards

**Comment by swizzard** [comment]
LGTM! Thank you!
